### ISSUE TITLE
Components Object Example incorrect

### ISSUE THREAD

**Issue by gcatanese** [OAI/sig-workflows#140]
It appears that Components Object [Example](https://github.com/OAI/sig-workflows/blob/main/versions/1.0.0.md#components-object-example) is incorrect. 

Components `inputs` is defined as map of Parameter objects while `parameters` is defined as map of Schema, shouldn't that be the other way around?

```
components:
  inputs:
    storeId:
      name: storeId
      in: header
      value: $inputs.x-store-id
  parameters:
    pagination:
      type: object
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
```
