### ISSUE TITLE
Feedback on `operationPath`

### ISSUE THREAD

**Issue by RomanHotsiy** [OAI/sig-workflows#179]
Hey folks 🙌 !

I've noticed you added support for `operationPath` for ability to target operations without operationId using JSON Pointer.

I have some feedback based on our experience working with this kind of format (JSON Pointer).

We have our users constantly confused about the correct format for the pointer:

- they either forget to escape  pointers at all `#/paths/pet/findByStatus/get`
- they realize they need to escape the JSON pointer but they miss the leading slash: `#/paths/pet~1findByStatus/get`

What we ended up using is to use separate values for path and HTTP verbs. In our WIP implementation we added support for:

```yaml
x-operation:
  sourceDescription: petStoreDescription # optional if only one sourceDescription is defined
  path: /pet/findByStatus
  method: get
```

I think this approach should work for the future versions of OpenAPI too.
What do you think about it? I can open PR with adjustments if you like it!
